package com.vilync.ophthalmicerp.data.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey


/**
 * Central Audit Trail for the complete ViLYNC ERP.
 *
 * This table is intentionally module-independent.
 *
 * It can record actions from:
 *
 * PURCHASE
 * PURCHASE_RETURN
 * DEBIT_NOTE
 * SALES
 * SALES_RETURN
 * CREDIT_NOTE
 * INVENTORY
 * PRODUCT_MASTER
 * PARTY_MASTER
 * PAYMENT
 * RECEIPT
 * SECURITY
 * SETTINGS
 * and future ERP modules.
 *
 * IMPORTANT:
 *
 * Audit records should normally never be physically deleted.
 */
@Entity(
    tableName = "audit_trail",
    indices = [
        Index(value = ["module"]),
        Index(value = ["action"]),
        Index(value = ["recordId"]),
        Index(value = ["userId"]),
        Index(value = ["financialYear"]),
        Index(value = ["createdAt"])
    ]
)
data class AuditTrailEntity(

    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,


    // =========================================================
    // MODULE / ACTION
    // =========================================================

    /**
     * Examples:
     *
     * PURCHASE
     * PURCHASE_RETURN
     * SALES
     * SALES_RETURN
     * PRODUCT_MASTER
     * PARTY_MASTER
     * SECURITY
     */
    val module: String,


    /**
     * Examples:
     *
     * CREATE
     * UPDATE
     * DELETE
     * RESTORE
     * CANCEL
     * LOGIN
     * LOGOUT
     */
    val action: String,


    // =========================================================
    // RECORD REFERENCE
    // =========================================================

    /**
     * Database ID of the affected record.
     *
     * Nullable because some security/system events may not
     * belong to a particular transaction record.
     */
    val recordId: Long? = null,


    /**
     * Human-readable document/reference.
     *
     * Examples:
     *
     * Purchase Invoice: LF/4587
     * Debit Note: DN-2026-001
     * Credit Note: CN-2026-001
     */
    val referenceNumber: String? = null,


    // =========================================================
    // USER
    // =========================================================

    val userId: Long? = null,

    val username: String? = null,

    val userDisplayName: String? = null,

    val userRole: String? = null,


    // =========================================================
    // FINANCIAL YEAR
    // =========================================================

    /**
     * Example:
     *
     * 2026-27
     */
    val financialYear: String? = null,


    // =========================================================
    // CHANGE DETAILS
    // =========================================================

    /**
     * Optional short description of what happened.
     *
     * Example:
     *
     * "Purchase invoice created"
     *
     * "Purchase Return created for 3 IOLs"
     */
    val description: String? = null,


    /**
     * Optional field name when a specific field changes.
     *
     * Example:
     *
     * invoiceNumber
     * quantity
     * expiryDate
     */
    val fieldName: String? = null,


    /**
     * Previous value for UPDATE actions.
     */
    val oldValue: String? = null,


    /**
     * New value for UPDATE actions.
     */
    val newValue: String? = null,


    // =========================================================
    // DATE / TIME
    // =========================================================

    /**
     * Epoch milliseconds.
     *
     * Audit time is generated by the ERP itself and should not
     * be editable by the normal user.
     */
    val createdAt: Long = System.currentTimeMillis()
)